### ISSUE TITLE
Configuration issue

### ISSUE THREAD

**Issue by FernandoGambaro** [nicoribeiro/java_efactura_uy#2]
Buenas, en el archivo README.md, indicas la configuración para conectar con mysql, pero no esta funcionando. (utilizando Ubuntu 18.04)
He agregado el driver jdbc al CLASSPATH y no lo reconoce (com.mysql.cj.jdbc.Driver), no he podido darme cuenta cómo configurarlo adecuadamente.
El error que da es Configuration error[Driver not found: [com.mysql.cj.jdbc.Driver}]]
He probado usando com.mysql.jdbc.Driver, con el mismo resultado
Podrías darme alguna pista?

Gracias

**Comment by nicoribeiro** [comment]
Hola Fernando,

El problema es que no estaba en las dependencias (build.sbt). En breves meto un commit con este arreglo y los cambios en el readme.  Voy a poner el driver com.mysql.jdbc.Driver que creo es más conocido que el otro.

Saludos!

**Comment by nicoribeiro** [comment]
Pronto, deberia estar resuelto en este [commit](https://github.com/nicoribeiro/java_efactura_uy/commit/07121659d2432107b66e4bb59528b0b4f84fc123)

**Comment by FernandoGambaro** [comment]
Muchas gracias, lo pruebo y te comento

**Comment by FernandoGambaro** [comment]
Probe y funcionó bien, gracias, sigo adelante, cualquier otra cosa te consulta.
Gracias por todo, el proyecto y tu ayuda
Saludos

**Comment by nicoribeiro** [comment]
Arriba Fernando. Buenísimo. 
Happy Coding!
