### ISSUE TITLE
Instalar

### ISSUE THREAD

**Issue by davidmonterocrespo24** [nicoribeiro/java_efactura_uy#4]
Hola, 
quiero comenzar a probar el proyecto.

En el paso 1 - >Create an rsa key and the PKCS10 request
Esa información puede ser ficticia o es necesario por ejemplo que el número de RUC sea  verdadero? puede ser mi número de cedula?

En el paso 4 - Go to Abitab webpage, select Request PKCS10 and fill the forms. When the page ask you for your PKCS10 request do...
Que opción se deberia elegir?
![image](https://user-images.githubusercontent.com/47928504/72177123-cc24fb80-33be-11ea-99e2-ca8c5782f74d.png)

Gracias

**Comment by nicoribeiro** [comment]
Hola David,
Respondo a tus preguntas:
1- Es necesario que sea información real ya que abitab te solicitara que presentes cierta documentación probatoria de que eres dueño de ese RUT.

2- Para la pagina que presentas debes de elegir la izquierda si eres una empresa y la derecha si eres un profesional/unipersonal.

Saludos!
