### ISSUE TITLE
Agregar annotations @Tx a clase HomologacionController

### ISSUE THREAD

**Issue by rmartony** [nicoribeiro/java_efactura_uy#5]
Agregar las siguientes líneas al archivo app/com/bluedot/efactura/controllers/HomologacionController.java

```
@ErrorMessage
@Tx
@Security.Authenticated(Secured.class)
```

**Comment by nicoribeiro** [comment]
resuelto en el commit 4e12ab1646e7644c63cb56a288ac879b62218f7f
