### ISSUE TITLE
[Question] Portar a PHP

### ISSUE THREAD

**Issue by alvaro-canepa** [nicoribeiro/java_efactura_uy#7]
Buenas, necesitaría implementar efactura en un proyecto en desarrollo. He estado tratando de buscar información en la web de dgi pero, a pesar que no trabajo con java, me es mas simple leer tu código para tener mejores referencias ;)  
Mi consulta es la siguiente, ¿podrías guiarme sobre el api de eFactura?.   
No se que tema tienen los de dgi, que es todo a pdf, no publican una documentación en linea de su api, algo para desarrolladores, no para abogados...

Muchas gracias!!!

**Comment by nicoribeiro** [comment]
Hola Alvaro!

Te guío un poco, la API de DGI es SOAP, están los XSD y los WSDL en la vuelta para que puedas generar clases con alguna biblioteca de tu elección. Yo en java use xjc que viene en la JDK de java. Imagino que en PHP tendrás algo similar. 

Luego, este projecto en su version mas simple es un wrapper de esta API SOAP convirtiendola en una API Rest con JSON.

Una opcion es instalar java_efactura_uy como un servicio en alguna instancia dentro de tu arquitectura y que tu soft PHP le pegue a esta API. 

Suerte!

**Comment by alvaro-canepa** [comment]
Muchísimas gracias @nicoribeiro  
Encontré un par de librerías que estaré estudiando a ver cual implemento.
