### ISSUE TITLE
Agregar certificado Abitab a la aplicación

### ISSUE THREAD

**Issue by Diegofr104** [nicoribeiro/java_efactura_uy#8]
Buenas, quería saber en donde tengo que agregar el certificado de Abitab.

en los pasos a seguir esta "Add your Company, Configure your certificate" quería saber como es que agrego a la empresa y pongo o configuro el certificado en la app.

**Comment by nicoribeiro** [comment]
Hola Diego como estas?

Veo lo que decis. esta super pobre la doc en esos pasos. No solo eso, revisando los endpoints veo que no tenemos un POST en empresas para crear una nueva. Lo voy a agregar como un pendiente para el proximo release. En el interin lo que te recomiendo para no quedar trancado ir a la BBDD y agregar una entrada en la tabla empresas. Luego podes cargar todos los datos usando el PUT del endpoint de empresa. Incluso este endpoint (el PUT) te permite agregar el certificado que te dio abitab o el correo.

Saludos!

**Comment by Diegofr104** [comment]
Dale, Gracias!
